// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7owgizszYHHQb_rjGwlSfVvIICAihcQ',
    appId: '1:221404811471:web:534a6b03a8b4aa1da1e7ba',
    messagingSenderId: '221404811471',
    projectId: 'forfirebase-33e40',
    authDomain: 'forfirebase-33e40.firebaseapp.com',
    storageBucket: 'forfirebase-33e40.appspot.com',
    measurementId: 'G-87GHVXX0NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ltifLemdzyoxbZnbncaHZvMOW2iXYkw',
    appId: '1:221404811471:android:be8200062b5587bea1e7ba',
    messagingSenderId: '221404811471',
    projectId: 'forfirebase-33e40',
    storageBucket: 'forfirebase-33e40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zXRA-Fmq3kOjxfKePrwdr3aSGklTiKM',
    appId: '1:221404811471:ios:4fd33113cc26a973a1e7ba',
    messagingSenderId: '221404811471',
    projectId: 'forfirebase-33e40',
    storageBucket: 'forfirebase-33e40.appspot.com',
    iosBundleId: 'com.example.forfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zXRA-Fmq3kOjxfKePrwdr3aSGklTiKM',
    appId: '1:221404811471:ios:4fd33113cc26a973a1e7ba',
    messagingSenderId: '221404811471',
    projectId: 'forfirebase-33e40',
    storageBucket: 'forfirebase-33e40.appspot.com',
    iosBundleId: 'com.example.forfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI7owgizszYHHQb_rjGwlSfVvIICAihcQ',
    appId: '1:221404811471:web:1e07815ee789b04aa1e7ba',
    messagingSenderId: '221404811471',
    projectId: 'forfirebase-33e40',
    authDomain: 'forfirebase-33e40.firebaseapp.com',
    storageBucket: 'forfirebase-33e40.appspot.com',
    measurementId: 'G-8V7Y6GM05N',
  );
}
